site_name: libmineshaft 
theme: readthedocs
nav:
    - Home: "index.md"
    - Getting Started:    
        - Installation: "install.md"
    - Basics:
        - Blocks: "blocks.md"
    - Advanced:
        - Shell: "shell.md"
