site_name: libmineshaft Documentation
theme: readthedocs
nav:
    - Welcome to libmineshaft's documentation: "index.md"
    - Getting Started:    
        - Installation: "install.md"
    
    - Advanced:
        - Shell: "shell.md"
